import tkinter as tk
root=tk.Tk()
root.title("My_Calculator")
def button_click(val):
    cur=entry.get()
    entry.delete(0, tk.END)
    entry.insert(0, cur + val)
def button_equal():
    try:
        res=eval(entry.get())
        entry.delete(0, tk.END)
        entry.insert(0, str(res))
    except:
        entry.delete(0, tk.END)
        entry.insert(0, "Error:Invalid input")
def button_clear():
    entry.delete(0, tk.END)
entry = tk.Entry(root, width=20, font=('Arial', 18), borderwidth=5, justify='right')
entry.grid(row=0, column=0, columnspan=4, padx=10, pady=10)
button0=tk.Button(root,text="0",command=lambda:button_click("0"))
button0.grid(row=4, column=1, sticky='nsew')
button1=tk.Button(root,text="1",command=lambda:button_click("1"))
button1.grid(row=3, column=0, sticky='nsew')
button2=tk.Button(root,text="2",command=lambda:button_click("2"))
button2.grid(row=3, column=1, sticky='nsew')
button3=tk.Button(root,text="3",command=lambda:button_click("3"))
button3.grid(row=3, column=2, sticky='nsew')
button4=tk.Button(root,text="4",command=lambda:button_click("4"))
button4.grid(row=2, column=0, sticky='nsew')
button5=tk.Button(root,text="5",command=lambda:button_click("5"))
button5.grid(row=2, column=1, sticky='nsew')
button6=tk.Button(root,text="6",command=lambda:button_click("6"))
button6.grid(row=2, column=2, sticky='nsew')
button7=tk.Button(root,text="7",command=lambda:button_click("7"))
button7.grid(row=1, column=0, sticky='nsew')
button8=tk.Button(root,text="8",command=lambda:button_click("8"))
button8.grid(row=1, column=1, sticky='nsew')
button9=tk.Button(root,text="9",command=lambda:button_click("9"))
button9.grid(row=1, column=2, sticky='nsew')
button10=tk.Button(root,text="=",command=lambda:button_equal())
button10.grid(row=4, column=2, sticky='nsew')
button11=tk.Button(root,text="+",command=lambda:button_click("+"))
button11.grid(row=4, column=3, sticky='nsew')
button12=tk.Button(root,text="/",command=lambda:button_click("/"))
button12.grid(row=1, column=3, sticky='nsew')
button13=tk.Button(root,text="*",command=lambda:button_click("*"))
button13.grid(row=2, column=3, sticky='nsew')
button14=tk.Button(root,text="-",command=lambda:button_click("-"))
button14.grid(row=3, column=3, sticky='nsew')
button15=tk.Button(root,text="C",command=lambda:button_clear())
button15.grid(row=4, column=0, sticky='nsew')
root.mainloop()
